# Generated by Django 3.1.2 on 2021-01-01 12:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=50, unique=True)),
                ('club_description', models.TextField()),
                ('club_tags', models.CharField(max_length=200)),
                ('logo', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ('club_name',),
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('bilkent_id', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 8', regex='^[0-9]{8}$')])),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('bilkent_id',),
                'unique_together': {('first_name', 'last_name')},
            },
        ),
        migrations.CreateModel(
            name='RecommendedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50, unique=True)),
                ('event_place', models.TextField()),
                ('event_time', models.DateTimeField()),
                ('event_points', models.PositiveIntegerField(default=0)),
                ('event_max_capacity', models.PositiveIntegerField(default=0)),
                ('event_description', models.TextField(default='')),
                ('event_tags', models.CharField(max_length=200)),
                ('event_zoom_link', models.URLField(blank=True, null=True)),
                ('event_current_capacity', models.PositiveIntegerField(default=0)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BilEventsApp.club')),
                ('users', models.ManyToManyField(blank=True, null=True, related_name='recommended_users', to='BilEventsApp.Participant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='club',
            name='club_members',
            field=models.ManyToManyField(blank=True, null=True, related_name='club_members', to='BilEventsApp.Participant'),
        ),
        migrations.AddField(
            model_name='club',
            name='leader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BilEventsApp.participant'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50, unique=True)),
                ('event_place', models.TextField()),
                ('event_time', models.DateTimeField()),
                ('event_points', models.PositiveIntegerField(default=0)),
                ('event_max_capacity', models.PositiveIntegerField(default=0)),
                ('event_description', models.TextField(default='')),
                ('event_tags', models.CharField(max_length=200)),
                ('event_zoom_link', models.URLField(blank=True, null=True)),
                ('event_current_capacity', models.PositiveIntegerField(default=0)),
                ('event_score', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BilEventsApp.club')),
                ('participants', models.ManyToManyField(blank=True, null=True, related_name='event_participants', to='BilEventsApp.Participant')),
            ],
            options={
                'ordering': ('event_time',),
                'unique_together': {('event_name',)},
            },
        ),
        migrations.AlterUniqueTogether(
            name='club',
            unique_together={('club_name', 'logo', 'leader')},
        ),
    ]
