# Generated by Django 3.1.2 on 2020-12-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BilEventsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='./staticfiles/rest_framework/img'),
        ),
    ]
