# Generated by Django 3.1.2 on 2020-12-20 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BilEventsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recommendedevent',
            name='event_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='bilkent_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 8', regex='^[0-9]{8}$')]),
        ),
    ]
