# Generated by Django 3.1.2 on 2020-11-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BilEventsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
