# Generated by Django 3.1.2 on 2021-01-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BilEventsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, to='BilEventsApp.Participant'),
        ),
    ]
