# Generated by Django 3.1.2 on 2020-12-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BilEventsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('first_name', 'last_name')},
        ),
    ]
