# Generated by Django 3.1.2 on 2021-01-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BilEventsApp', '0002_auto_20210101_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='event_participants', to='BilEventsApp.Participant'),
        ),
    ]
