# Generated by Django 3.1.2 on 2021-01-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BilEventsApp', '0003_auto_20210101_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_current_capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='recommendedevent',
            name='event_current_capacity',
            field=models.PositiveIntegerField(),
        ),
    ]
