# Generated by Django 3.1.2 on 2020-12-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BilEventsApp', '0004_auto_20201221_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='pp',
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
