# Generated by Django 3.1.2 on 2021-01-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BilEventsApp', '0005_auto_20210101_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendedevent',
            name='club',
        ),
        migrations.RemoveField(
            model_name='recommendedevent',
            name='event_current_capacity',
        ),
        migrations.RemoveField(
            model_name='recommendedevent',
            name='event_description',
        ),
        migrations.RemoveField(
            model_name='recommendedevent',
            name='event_max_capacity',
        ),
        migrations.RemoveField(
            model_name='recommendedevent',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='recommendedevent',
            name='event_place',
        ),
        migrations.RemoveField(
            model_name='recommendedevent',
            name='event_points',
        ),
        migrations.RemoveField(
            model_name='recommendedevent',
            name='event_tags',
        ),
        migrations.RemoveField(
            model_name='recommendedevent',
            name='event_time',
        ),
        migrations.RemoveField(
            model_name='recommendedevent',
            name='event_zoom_link',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_current_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
